--------------------------------------------------------
--  File created - Thursday-October-18-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TASK_GROUP
--------------------------------------------------------

  CREATE TABLE "PMTL2"."TASK_GROUP" 
   (	"TASK_GROUP_ID" NUMBER, 
	"TASK_GROUP_NAME" NVARCHAR2(1000), 
	"TASK_GROUP_CONTENT" NVARCHAR2(2000), 
	"DEPARTMENT" NVARCHAR2(1000), 
	"PERIODIC" NUMBER(6,0), 
	"END_TASK_GROUP" NUMBER(6,0), 
	"START_TASK_GROUP" NUMBER(6,0), 
	"WARNING_TASK_GROUP" NUMBER(6,0), 
	"WARNING_CYCLE" NUMBER(6,0), 
	"WARNING_EMAIL" VARCHAR2(4000 BYTE), 
	"DEPARTMENT_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into PMTL2.TASK_GROUP
SET DEFINE OFF;
Insert into PMTL2.TASK_GROUP (TASK_GROUP_ID,TASK_GROUP_NAME,TASK_GROUP_CONTENT,DEPARTMENT,PERIODIC,END_TASK_GROUP,START_TASK_GROUP,WARNING_TASK_GROUP,WARNING_CYCLE,WARNING_EMAIL,DEPARTMENT_ID) values (3,'Báo cáo chi tiêu tháng','báo cáo chi tiêu thực đơn tháng cho phòng kế toán và tài chính','Phòng Hành chính',2,22,17,20,1,'atranviettel001@gmail.com,btranviettel002@gmail.com',271134);
Insert into PMTL2.TASK_GROUP (TASK_GROUP_ID,TASK_GROUP_NAME,TASK_GROUP_CONTENT,DEPARTMENT,PERIODIC,END_TASK_GROUP,START_TASK_GROUP,WARNING_TASK_GROUP,WARNING_CYCLE,WARNING_EMAIL,DEPARTMENT_ID) values (1,'Update code','update code các phần mềm  cho tổng công ty CT ,','Phòng Công nghệ thông tin',1,5,2,3,2,'atranviettel001@gmail.com,btranviettel002@gmail.com',271140);
Insert into PMTL2.TASK_GROUP (TASK_GROUP_ID,TASK_GROUP_NAME,TASK_GROUP_CONTENT,DEPARTMENT,PERIODIC,END_TASK_GROUP,START_TASK_GROUP,WARNING_TASK_GROUP,WARNING_CYCLE,WARNING_EMAIL,DEPARTMENT_ID) values (2,'Báo cáo doanh thu','báo cáo doanh thu tháng  cho ban giám đốc','Phòng Tài chính Kế toán',2,20,10,26,1,'atranviettel001@gmail.com,btranviettel002@gmail.com',271152);
--------------------------------------------------------
--  DDL for Index TASK_GROUP_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PMTL2"."TASK_GROUP_PK" ON "PMTL2"."TASK_GROUP" ("TASK_GROUP_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table TASK_GROUP
--------------------------------------------------------

  ALTER TABLE "PMTL2"."TASK_GROUP" MODIFY ("TASK_GROUP_ID" NOT NULL ENABLE);
 
  ALTER TABLE "PMTL2"."TASK_GROUP" ADD CONSTRAINT "TASK_GROUP_PK" PRIMARY KEY ("TASK_GROUP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
